version: '3'

services:
        backend:
                image: ubuntu:16.04
                build: /home/jussi/Projects/Docker/Part1/1.11/
                ports: 
                 - 8000:8000  
                environment:
                 - FRONT_URL=http://localhost:5000
                 - REDIS=redis 
                 - REDIS_PORT=6379
                 - DB_USERNAME=jussi
                 - DB_PASSWORD=1234
                 - DB_HOST=db_backend  
                depends_on:
                 - db

        frontend:
                build: /home/jussi/Projects/Docker/Part1/1.10/
                ports:
                 - 5000:5000
                environment:
                 - API_URL=http://localhost:8000
        redis:
                image: redis:latest
                ports:
                 - 6379:6379
        db:
                image: postgres
                restart: unless-stopped
                container_name: db_backend
                environment:
                 - POSTGRES_USER=jussi       
                 - POSTGRES_PASSWORD=1234
        proxy:
                image: jwilder/nginx-proxy
                volumes: 
                 - /var/run/docker.sock:/tmp/docker.sock:ro
                 - ./nginx.conf:/etc/nginx/nginx.conf
                ports: 
                 - 80:80
                depends_on: 
                 - frontend
                 - backend
volumes:
  database:
