version: '3'

services:
        frontend:
                image: ubuntu:16.04
                build: /home/jussi/Projects/Docker/Part1/1.10/
                ports:
                 - 5000:5000
                environment:
                 - API_URL=http://localhost:8000
        backend:
                image: ubuntu:16.04
                build: /home/jussi/Projects/Docker/Part1/1.11/
                ports: 
                 - 8000:8000
                environment:
                 - FRONT_URL=http://localhost:5000
