version: '3.5'

services: 
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports: 
     - 3000:3000
  backend:
    build: ./ml-kurkkumopo-backend
    volumes:
     - ./model:/src/model 
    ports:
     - 5000:5000
    depends_on: 
     - training
  training:
    build: ./ml-kurkkumopo-training
    volumes: 
     - ./images:/src/imgs
     - ./ml-kurkkumopo-training/data:/data
     - ./model:/src/model

volumes:
  model:
  images:
  data:
  model:
